- name: Instalar Jellyfin local
  hosts: localhost
  become: true

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Iniciar Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Crear carpeta media
      file:
        path: /home/ubuntu/media
        state: directory

    - name: Correr contenedor Jellyfin
      community.docker.docker_container:
        name: jellyfin-container
        image: jellyfin/jellyfin
        state: started
        ports:
          - "8096:8096"
        volumes:
          - /home/ubuntu/media:/media
        restart_policy: unless-stopped
